[2023-11-26T19:13:37.869+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.download_currency manual__2023-11-26T19:08:35.255504+00:00 [queued]>
[2023-11-26T19:13:37.873+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.download_currency manual__2023-11-26T19:08:35.255504+00:00 [queued]>
[2023-11-26T19:13:37.873+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-11-26T19:13:37.880+0000] {taskinstance.py:1380} INFO - Executing <Task(DownloadCurrencyOperator): download_currency> on 2023-11-26 19:08:35.255504+00:00
[2023-11-26T19:13:37.884+0000] {standard_task_runner.py:57} INFO - Started process 223 to run task
[2023-11-26T19:13:37.886+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'download_currency', 'manual__2023-11-26T19:08:35.255504+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpamk4kuny']
[2023-11-26T19:13:37.888+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask download_currency
[2023-11-26T19:13:37.918+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_dag.download_currency manual__2023-11-26T19:08:35.255504+00:00 [running]> on host e90f0e94c48e
[2023-11-26T19:13:37.962+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='download_currency' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T19:08:35.255504+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T19:08:35.255504+00:00'
[2023-11-26T19:13:38.430+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/custom_operators.py", line 77, in execute
    download_currency_to_csv()
  File "/opt/airflow/dags/custom_operators.py", line 14, in download_currency_to_csv
    currency_data.to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/data'
[2023-11-26T19:13:38.443+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=download_currency, execution_date=20231126T190835, start_date=20231126T191337, end_date=20231126T191338
[2023-11-26T19:13:38.451+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 54 for task download_currency (Cannot save file into a non-existent directory: '/data'; 223)
[2023-11-26T19:13:38.463+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T19:13:38.477+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
