[2023-11-26T19:12:05.989+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.download_currency manual__2023-11-26T19:12:04.562506+00:00 [queued]>
[2023-11-26T19:12:05.995+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.download_currency manual__2023-11-26T19:12:04.562506+00:00 [queued]>
[2023-11-26T19:12:05.995+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-26T19:12:06.004+0000] {taskinstance.py:1380} INFO - Executing <Task(DownloadCurrencyOperator): download_currency> on 2023-11-26 19:12:04.562506+00:00
[2023-11-26T19:12:06.008+0000] {standard_task_runner.py:57} INFO - Started process 178 to run task
[2023-11-26T19:12:06.013+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'download_currency', 'manual__2023-11-26T19:12:04.562506+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_21m0emy']
[2023-11-26T19:12:06.016+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask download_currency
[2023-11-26T19:12:06.054+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_dag.download_currency manual__2023-11-26T19:12:04.562506+00:00 [running]> on host e90f0e94c48e
[2023-11-26T19:12:06.277+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='download_currency' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T19:12:04.562506+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T19:12:04.562506+00:00'
[2023-11-26T19:12:06.399+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/custom_operators.py", line 77, in execute
    download_currency_to_csv()
  File "/opt/airflow/dags/custom_operators.py", line 14, in download_currency_to_csv
    currency_data.to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/data'
[2023-11-26T19:12:06.410+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_dag, task_id=download_currency, execution_date=20231126T191204, start_date=20231126T191205, end_date=20231126T191206
[2023-11-26T19:12:06.418+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 51 for task download_currency (Cannot save file into a non-existent directory: '/data'; 178)
[2023-11-26T19:12:06.468+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T19:12:06.484+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
